In [ ]:
print('hello world!')

hello world!


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [ ]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)
X

array([[ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
         0.97024255,  0.02188649],
       [-1.00280393, -0.57873591,  1.74273971, ..., -1.54776799,
         0.97024255,  0.21653375],
       [ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [ 0.99720391, -0.57873591, -0.57380915, ..., -1.54776799,
         0.97024255, -1.00864308],
       [-1.00280393,  1.72790383, -0.57380915, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
        -1.03067011, -1.07636976]])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
import tensorflow as tf
ann = tf.keras.models.Sequential()

In [ ]:
ann.add(tf.keras.layers.Dense(units=11, activation = 'relu'))
ann.add(tf.keras.layers.Dense(units=11, activation = 'relu'))
ann.add(tf.keras.layers.Dense(units=11, activation = 'relu'))
ann.add(tf.keras.layers.Dense(units=1, activation = 'sigmoid'))

In [ ]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])


In [ ]:
ann.fit(X_train, y_train, batch_size=32, epochs=10)


Epoch 1/10
250/250 [==============================] - 2s 2ms/step - loss: 0.5771 - accuracy: 0.6945
Epoch 2/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4560 - accuracy: 0.7968
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.4359 - accuracy: 0.7965
Epoch 4/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4218 - accuracy: 0.8099
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.4043 - accuracy: 0.8299
Epoch 6/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3850 - accuracy: 0.8382
Epoch 7/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3685 - accuracy: 0.8446
Epoch 8/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3580 - accuracy: 0.8490
Epoch 9/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3488 - accuracy: 0.8537
Epoch 10/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3437 - accuracy: 0.8564

In [ ]:
pd.DataFrame(X_test)

0         1         2         3         4         5         6   \
0    -1.002804  1.727904 -0.573809 -0.553850 -1.095988 -0.373958  1.032908   
1     0.997204 -0.578736 -0.573809 -1.319512 -1.095988  0.102810 -1.041760   
2    -1.002804 -0.578736  1.742740  0.573948 -1.095988  0.293517  1.032908   
3     0.997204 -0.578736 -0.573809  1.422384  0.912419 -0.660018 -0.350204   
4    -1.002804  1.727904 -0.573809  0.573948  0.912419 -0.087897 -0.004426   
...        ...       ...       ...       ...       ...       ...       ...   
1995  0.997204 -0.578736 -0.573809 -0.264141 -1.095988 -1.422847 -1.387538   
1996  0.997204 -0.578736 -0.573809 -0.667665 -1.095988 -0.373958  0.687130   
1997 -1.002804 -0.578736  1.742740 -0.750439  0.912419 -0.278604 -1.387538   
1998 -1.002804  1.727904 -0.573809 -0.005471  0.912419 -0.469311 -0.350204   
1999 -1.002804  1.727904 -0.573809 -0.802173  0.912419 -0.850726  1.032908   

            7         8         9         10        11  
0     0.875323 -0.911583  0.646092  0.970243  1.613046  
1     0.424422 -0.911583  0.646092 -1.030670  0.497532  
2     0.302927 -0.911583  0.646092  0.970243 -0.423561  
3     0.570464 -0.911583 -1.547768 -1.030670 -0.186439  
4     1.387129  0.807737  0.646092  0.970243  0.618560  
...        ...       ...       ...       ...       ...  
1995 -1.225848  0.807737  0.646092  0.970243  1.406410  
1996 -1.225848  0.807737  0.646092 -1.030670 -0.510012  
1997  1.294703  0.807737  0.646092 -1.030670  0.720651  
1998  1.056302 -0.911583  0.646092  0.970243 -1.544383  
1999  0.816110 -0.911583  0.646092 -1.030670  1.614749  

[2000 rows x 12 columns]

In [ ]:
ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))

1/1 [==============================] - 0s 132ms/step


array([[0.08578576]], dtype=float32)

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)

63/63 [==============================] - 0s 4ms/step


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
cm

array([[1584,   11],
       [ 331,   74]])

In [ ]:
accuracy_score(y_test, y_pred)

0.829